# Generated by Django 6.0.4 on 2026-04-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('IMPORTACAO', 'Importação'), ('EXPORTACAO', 'Exportação')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moeda', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(default='Em andamento', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
