# Generated by Django 6.0.4 on 2026-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_processo_data_emissao_processo_referencia_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='data_fatura',
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_fatura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
