# Generated by Django 6.0.4 on 2026-04-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_emissao', '-id']},
        ),
        migrations.AddField(
            model_name='processo',
            name='cia_aerea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='draft_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='etd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='modal',
            field=models.CharField(blank=True, choices=[('MARITIMO', 'Marítimo'), ('AEREO', 'Aéreo'), ('RODOVIARIO', 'Rodoviário')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='pendencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='pre_alerta_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='processo',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='si_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='status_operacional',
            field=models.CharField(choices=[('AGUARDANDO_BOOKING', 'Aguardando booking'), ('BOOKING_CONFIRMADO', 'Booking confirmado'), ('DRAFT_CONFERENCIA', 'Draft em conferência'), ('SI_PENDENTE', 'SI pendente'), ('PRE_ALERTA_PENDENTE', 'Pré-alerta pendente'), ('EMBARCADO', 'Embarcado'), ('CHEGADA_PENDENTE', 'Chegada pendente'), ('FATURAMENTO_PENDENTE', 'Faturamento pendente'), ('FINALIZADO', 'Finalizado'), ('ATRASADO', 'Atrasado')], default='AGUARDANDO_BOOKING', max_length=30),
        ),
        migrations.AddField(
            model_name='processo',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='core.processo')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_operacionais', to='core.processo')),
            ],
            options={
                'verbose_name': 'Tarefa Operacional',
                'verbose_name_plural': 'Tarefas Operacionais',
                'ordering': ['prazo', '-criado_em'],
            },
        ),
    ]
