# Generated by Django 6.0.4 on 2026-04-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_processo_options_processo_cia_aerea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='contareceber',
            options={'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterModelOptions(
            name='cotacaocambio',
            options={'verbose_name': 'Câmbio da Cotação', 'verbose_name_plural': 'Câmbios da Cotação'},
        ),
        migrations.AlterModelOptions(
            name='cotacaomoeda',
            options={'verbose_name': 'Cotação de Moeda', 'verbose_name_plural': 'Cotações de Moeda'},
        ),
        migrations.AlterModelOptions(
            name='custocotacao',
            options={'verbose_name': 'Custo da Cotação', 'verbose_name_plural': 'Custos da Cotação'},
        ),
        migrations.AlterModelOptions(
            name='dadosbancarios',
            options={'verbose_name': 'Dado Bancário', 'verbose_name_plural': 'Dados Bancários'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Follow-up', 'verbose_name_plural': 'Follow-ups'},
        ),
        migrations.AlterModelOptions(
            name='itemcotacao',
            options={'verbose_name': 'Item da Cotação', 'verbose_name_plural': 'Itens da Cotação'},
        ),
        migrations.AlterModelOptions(
            name='itemfatura',
            options={'verbose_name': 'Item da Fatura', 'verbose_name_plural': 'Itens da Fatura'},
        ),
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_emissao', '-id'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
    ]
