# Generated by Django 6.0.4 on 2026-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dadosbancarios_rename_moeda_processo_moeda_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_cotacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra Esterlina')], default='BRL', max_length=10),
        ),
        migrations.AlterField(
            model_name='processo',
            name='moeda_principal',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra Esterlina')], default='USD', max_length=10),
        ),
    ]
