# Generated by Django 6.0.4 on 2026-04-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_processo_data_cotacao_alter_itemfatura_moeda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoMoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra Esterlina')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='core.processo')),
            ],
        ),
    ]
