# Generated by Django 6.0.4 on 2026-04-20 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cotacaomoeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processo',
            name='referencia_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
