# Generated by Django 6.0.4 on 2026-04-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_processo_data_fatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='referencia',
        ),
    ]
