# Generated by Django 6.0.4 on 2026-04-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_processo_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra Esterlina')], default='BRL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='core.processo')),
            ],
        ),
    ]
