# Generated by Django 6.0.4 on 2026-04-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contapagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='data_cotacao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='navio',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='pickup_container',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='place_of_delivery',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='previsao_chegada',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='saida',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tarifa_cotacao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='valor_recebido',
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10),
        ),
        migrations.AlterField(
            model_name='cotacaomoeda',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cotacaomoeda',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='conta_corrente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10),
        ),
        migrations.AlterField(
            model_name='processo',
            name='iof_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='processo',
            name='moeda_principal',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_fatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20),
        ),
    ]
