# Generated by Django 6.0.4 on 2026-04-21 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_processo_container_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='container_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_cotacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='navio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='pickup_container',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='place_of_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='previsao_chegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='tarifa_cotacao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_fatura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('IMPORTACAO', 'Importação'), ('EXPORTACAO', 'Exportação')], max_length=20)),
                ('moeda_principal', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10)),
                ('tarifa_cotacao', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('data_cotacao', models.DateField(blank=True, null=True)),
                ('iof_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pol', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('transbordo', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.CharField(blank=True, max_length=100, null=True)),
                ('transit_time', models.CharField(blank=True, max_length=20, null=True)),
                ('armador', models.CharField(blank=True, max_length=100, null=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('previsao_chegada', models.DateField(blank=True, null=True)),
                ('container_type', models.CharField(blank=True, max_length=100, null=True)),
                ('navio', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_container', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('ENVIADA', 'Enviada'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='EM_ANALISE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('processo_gerado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacao_origem', to='core.processo')),
            ],
        ),
        migrations.CreateModel(
            name='CotacaoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_moeda', to='core.cotacao')),
            ],
        ),
        migrations.CreateModel(
            name='CustoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_cotacao', to='core.cotacao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('GBP', 'Libra')], default='BRL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_cotacao', to='core.cotacao')),
            ],
        ),
    ]
